### ISSUE TITLE
Who the hell even are you and why do you have so many starred repositories?

### ISSUE THREAD

**Issue by BenjaminAster** [insolitum/insolitum#5]
You have starred way over 5k repositories (GitHub doesn't show the exact number), including some of mine and _a lot_ of other small personal projects. Seems to me as if you wrote a bot that scrapes the internet for GitHub repositories and stars them automatically. That way, people who look at the stargazers of their repositories stumble upon your profile, follow you and star your stuff. Does GitHub not stop you from automatically starring tens of thousands of repositories? I'm pretty sure that's against their terms of service. Please stop doing that.

**Comment by 0dminnimda** [comment]
What is defenitely against the terms of service is asking those people to star them back
This is fishy as well tho
